### PR TITLE
#Updated Telegram.Bot to 15.5.1

### PR DESCRIPTION
**Pull request by Ezergil**
#Updated Net and NetStandard versions
#Made BlockingTelegramBotClient decorator over TelegramBotClient
#Implement all missing members from 15.5.1
#Fixed all inheritdocs

Hi, @MihaZupan 
You haven't updated this for two whole years, so i did it for you :)

Also, i made BlockingTelegramBotClient an adapter of Telegram.Bot client so it match SOLID principles (e.g. DIP, now it could be used in Unit Tests!)  and all inheritdoc are working now

Apreciate your work on this library code, i think it will help me alot in my projects :)
If you have any questions - feel free to mention me there

Waiting for nuget package update! 

Thanks in advance

### CODE REVIEW

**Comment by Ezergil** [comment]
@MihaZupan sorry, haven't checked https://github.com/TelegramBotExtensions/TelegramBotClients before creating this request

Still u could check it and merge to keep this project up to date :)

**Comment by MihaZupan** [comment]
Thanks for looking at this and sorry that it wasn't made obvious this repo is not up-to-date anymore in favour of https://github.com/TelegramBotExtensions/TelegramBotClients.

Is the SchedulingMethod feature something that you actually rely on? That is the only good part of the BlockingClient implementation.

In the actual repo (TelegramBotExtensions), that implementation has been replaced with [a new one](https://github.com/TelegramBotExtensions/TelegramBotClients/blob/2084260ab9ae113ba07d40871f2e849d4245c0f2/src/TelegramBotClients/RateLimitedClient/TelegramRequestScheduler.cs) that one can actually reason about. I am not confident the BlockingClient impl is actually 100% correct, and it also blocks, completely ruining the point of async and is as such a terrible implementation that I am not proud of.

Updating the [interface](https://github.com/TelegramBotExtensions/TelegramBotClients/blob/2084260ab9ae113ba07d40871f2e849d4245c0f2/src/TelegramBotClients/RateLimitedClient/RateLimitedTelegramBotClient.cs) to the new Telegram.Bot version is hopefully the only change that should happen there.

**Comment by Ezergil** [comment]
@MihaZupan thanks for your answer 
Currently I am testing implementation of RateLimit client and will answer in few days if it working fine 

The question is : are you sure telegram api limitations are also applied to methods like getchatadmonistators, getupdates and so on?

**Comment by MihaZupan** [comment]
> Currently I am testing implementation of RateLimit client and will answer in few days if it working fine

Thanks.

> The question is : are you sure telegram api limitations are also applied to methods like getchatadmonistators, getupdates and so on?

I don't. If anyone has tested and found out for sure that some methods are exempt, we can make the change for them.

**Comment by MihaZupan** [comment]
If there is a real need for scheduling priority with the new impl, that can be added as well

**Comment by Ezergil** [comment]
> If there is a real need for scheduling priority with the new impl, that can be added as well

I think things like this could be easily implemented on your library clients side 

The only reason I separated configuration of scheduled methods to request binding is because I’ve wanted to test SchedulingMethod.Ignore for get methods :))

So ok, I’ll try to find out about her methods and will keep you in sync

**Comment by Ezergil** [comment]
@MihaZupan could I create a pull request with Telegram.Bot version update to your actual repo? 
I’m using non-anonymous polls in my bot

**Comment by MihaZupan** [comment]
Yeah if it's just the updated method list that's perfect. There should be a project ready to generate the updated source for it in the repo.

**Pull request closed without merging**
